--Localization.frFR.lua
--From ckeurk

if ( GetLocale() == "frFR" ) then

TomTomLocals = {
    ["Acts as your portable navigation assistant"] = "Agit comme un assistant de navigation portable",
	["Accept waypoints from guild and party members"] = "Accepter les points de passage des membres de la guilde", -- Needs review
	["Allow closest waypoint to be outside current zone"] = "Laissez le plus proche point de passage \195\160 l'ext\195\169rieur de la zone actuelle", -- Needs review
	["Allow control-right clicking on map to create new waypoint"] = "Autoriser le contr\195\180le-clic droit sur la carte pour cr\195\169er un point de passage", -- Needs review
	["Allow the corpse arrow to override other waypoints"] = "Permettre \195\160 la fl\195\168che actuelle de remplacer d'autres points de passage", -- Needs review
	["Alpha"] = "Alpha", -- Needs review
	["Announce new waypoints when they are added"] = "Annonce de nouveaux points de passage quand ils sont ajout\195\169s", -- Needs review
	["Are you sure you would like to remove ALL TomTom waypoints?"] = "Etes-vous s\195\187r que vous voulez supprimer TOUS les points de passage dans TomTom?", -- Needs review
	["\"Arrival Distance\""] = "Distance d'arriv\195\169e", -- Needs review
	["Arrow colors"] = "Couleur de la fl\195\168che", -- Needs review
	["Arrow display"] = "Affichage de la fl\195\168che", -- Needs review
	["Ask for confirmation on \"Remove All\""] = "Demander confirmation avant de \"Tout supprimer !!\"", -- Needs review
	["Automatically set a waypoint when I die"] = "Demander une confirmation pour \"Tout supprimer !\"", -- Needs review
	["Automatically set to next closest waypoint"] = "R\195\169gl\195\169 automatiquement le prochain point de passage le plus proche", -- Needs review
	["Automatically set waypoint arrow"] = "R\195\169gle automatiquement la fl\195\168che du point de passage", -- Needs review
	["Background color"] = "Couleur d'arri\195\168re-plan", -- Needs review
	["Bad color"] = "Mauvaise direction", -- Needs review
	["Block height"] = "Hauteur du cadre", -- Needs review
	["Block width"] = "Largeur du cadre", -- Needs review
	["Border color"] = "Couleur de la bordure", -- Needs review
	["|cffffff78TomTom:|r Added a waypoint (%s%s%s) in %s"] = "|cffffff78TomTom:|r Ajout d'un point de passage (%s%s%s) dans %s", -- Needs review
	["|cffffff78TomTom|r: Added '%s' (sent from %s) to zone %s"] = "|cffffff78TomTom|r: Ajout\195\169 '%s' (envoyer \195\160 partir de %s) \195\160 la zone %s", -- Needs review
	["|cffffff78TomTom |r/way |cffffff78Usage:|r"] = "|cffffff78TomTom |r/way |cffffff78Utilisation:|r", -- Needs review
	["|cffffff78/way list|r - Lists active waypoints in current zone"] = "|cffffff78/way list|r - Listes des points actifs dans la zone actuelle", -- Needs review
	["|cffffff78/way reset all|r - Resets all waypoints"] = "|cffffff78/way reset all|r - R\195\169initialise tous les points de passage", -- Needs review
	["|cffffff78/way reset <zone>|r - Resets all waypoints in zone"] = "|cffffff78/way reset <zone>|r - R\195\169initialise tous les points dans la zone", -- Needs review
	["|cffffff78/way <x> <y> [desc]|r - Adds a waypoint at x,y with descrtiption desc"] = "|cffffff78/way <x> <y> [desc]|r - Ajoute un point de passage en x, y et la descrtiption", -- Needs review
	["|cffffff78/way <x> <y> -- L[desc]|r - Adds a waypoint at x,y with descrtiption desc"] = "|cffffff78/way <x> <y> -- L[desc]|r - Ajoute un point de passage en x, y avec la descrtiption", -- Needs review
	["|cffffff78/way <zone> <x> <y> [desc]|r - Adds a waypoint at x,y in zone with description desc"] = "|cffffff78/way <zone> <x> <y> [desc]|r - Ajoute un point de passage en x, y dans la zone avec la description", -- Needs review
	["|cffffff78/way <zone> <x> <y> -- L[desc]|r - Adds a waypoint at x,y in zone with description desc"] = "|cffffff78/way <zone> <x> <y> -- L[desc]|r - Ajoute un point de passage en x, y dans la zone avec la description", -- Needs review
	["Clear waypoint distance"] = "Effacer la distance du point de passage", -- Needs review
	["Clear waypoint from crazy arrow"] = "Effacer le point de passage de la fl\195\168che d\195\169traqu\195\169", -- Needs review
	["Controls the frequency of updates for the coordinate block."] = "Commande la fr\195\169quence des mises \195\160 jour pour le cadre des coordonn\195\169es.", -- Needs review
	["Controls the frequency of updates for the coordinate LDB feed."] = "Contr\195\180le la fr\195\169quence des mises \195\160 jour pour transmettre les coordonn\195\169es LDB.", -- Needs review
	-- ["Controls the frequency of updates for the crazy arrow LDB feed."] = "",
	["Coordinate Accuracy"] = "Pr\195\169cision des coordonn\195\169es", -- Needs review
	["Coordinate Block"] = "Fen\195\170tre de coordonn\195\169e", -- Needs review
	-- ["Coordinate feed accuracy"] = "",
	-- ["Coordinate feed throttle"] = "",
	["Coordinates can be displayed as simple XX, YY coordinate, or as more precise XX.XX, YY.YY.  This setting allows you to control that precision"] = "Les coordonn\195\169es peuvent \195\170tre affich\195\169s sous forme simple XX, YY coordonn\195\169e, ou plus pr\195\169cis XX.XX, YY.YY. Ce param\195\168tre vous permet de contr\195\180ler la pr\195\169cision ", -- Needs review
	["Could not find any matches for zone %s."] = "Impossible de trouver un point de passage correspondant dans cette zone %s.", -- Needs review
	-- ["Crazy Arrow feed throttle"] = "",
	["Create note modifier"] = "Raccourci clavier", -- Needs review
	["Cursor coordinate accuracy"] = "L'exactitude des coordonn\195\169es du curseur", -- Needs review
	["Cursor Coordinates"] = "Coordonn\195\169es du curseur", -- Needs review
	["Data Feed Options"] = "Options de flux de donn\195\169es", -- Needs review
	["Disable all mouse input"] = "D\195\169sactivez toutes les entr\195\169es de la souris", -- Needs review
	["Disables the crazy taxi arrow for mouse input, allowing all clicks to pass through"] = "D\195\169sactive la fl\195\168che (folle) au passage de la souris, permettant \195\160 tous les clics de passer \195\160 travers", -- Needs review
	["Display Settings"] = "Param\195\168tres d'affichage", -- Needs review
	["Display waypoints from other zones"] = "Afficher les points de passage des autres zones", -- Needs review
	["%d yards"] = "%d m\195\168tres", -- Needs review
	["Enable automatic quest objective waypoints"] = "Active automatiquement les points de passage des qu\195\170te de fa\195\167on objective", -- Needs review
	["Enable coordinate block"] = "Activer l'affichage du cadre de vos cordonn\195\169es", -- Needs review
	["Enable floating waypoint arrow"] = "Active la fl\195\168che des points de passage", -- Needs review
	["Enable minimap waypoints"] = "Active les points de passage sur la minicarte.", -- Needs review
	["Enable mouseover tooltips"] = "Activer les info-bulles ", -- Needs review
	["Enable quest objective click integration"] = "Activer l'int\195\169gration des qu\195\170te", -- Needs review
	["Enables a floating block that displays your current position in the current zone"] = "Affiche un cadre flottant qui donne votre position actuelle dans la zone actuelle",
	["Enables a menu when right-clicking on a waypoint allowing you to clear or remove waypoints"] = "Affiche une petite fen\195\170tre qui affiche votre position actuelle dans la zone actuelle", -- Needs review
	["Enables a menu when right-clicking on the waypoint arrow allowing you to clear or remove waypoints"] = "Active un menu (clic droit) sur la fl\195\168che qui vous permet d'effacer ou de supprimer des points de passage", -- Needs review
	["Enable showing cursor coordinates"] = "les coordonn\195\169es de votre curseur", -- Needs review
	["Enable showing player coordinates"] = "Affiche vos coordonn\195\169es", -- Needs review
	["Enables the automatic setting of quest objective waypoints based on which objective is closest to your current location.  This setting WILL override the setting of manual waypoints."] = "Active le r\195\169glage automatique des points de passage pour les objectifs de qu\195\170tes sur la base duquel l'objectif est le plus proche de votre position actuelle. Ce param\195\168tre remplace le param\195\168tre manuel.", -- Needs review
	["Enables the setting of waypoints when modified-clicking on quest objectives"] = "Permet le r\195\169glage des points de passaget une fois modifi\195\169e, en cliquant sur les objectifs de qu\195\170te", -- Needs review
	["Enable the right-click contextual menu"] = "Activer le menu contextuel du clic droit", -- Needs review
	["Enable world map waypoints"] = "Affiche sur la carte du monde les points de passage", -- Needs review
	["Exact color"] = "Direction exacte", -- Needs review
	["Font size"] = "taille de la police", -- Needs review
	["Found %d possible matches for zone %s.  Please be more specific"] = "J'ai rien trouv\195\169 %d  dans cette zone %s. Merci d'\195\170tre plus pr\195\169cis ! Gros poney ... Oups! pardon :)", -- Needs review
	["Found multiple matches for zone '%s'.  Did you mean: %s"] = "J'ai trouv\195\169 de multiple point de passage dans '%s'. Vouliez-vous dire: %s", -- Needs review
	["General Options"] = "Options g\195\169n\195\169rales", -- Needs review
	["Good color"] = "Bonne direction", -- Needs review
	["Hide the crazy arrow display during pet battles"] = "Masquer l'affichage de la fl\195\168che pendant les combats de mascotte", -- Needs review
	["If you have changed the waypoint display settings (minimap, world), this will re-set all waypoints to the current options."] = "Si vous avez chang\195\169 la fa\195\167on dont les param\195\168tres d'affichage des points de passage (mini-carte, monde), ce qui red\195\169finir tous les points de passage aux options actuelles.", -- Needs review
	["Lock coordinate block"] = "Verrouille le cadre de vos coordonn\195\169es", -- Needs review
	["Locks the coordinate block so it can't be accidentally dragged to another location"] = "Verrouille le cadre de vos coordonn\195\169es de sorte qu'il ne peut pas \195\170tre accidentellement entra\195\174n\195\169 vers un autre emplacement", -- Needs review
	["Locks the waypoint arrow, so it can't be moved accidentally"] = "Verrouille la fl\195\168che, de sorte qu'il ne peut pas \195\170tre d\195\169plac\195\169e accidentellement", -- Needs review
	["Lock waypoint arrow"] = "Verrouille la fl\195\168che ", -- Needs review
	["Middle color"] = "Direction moyenne", -- Needs review
	["Minimap"] = "Minicarte", -- Needs review
	["My Corpse"] = "Mon cadavre, Berk!",
	["No"] = "Non", -- Needs review
	["Normally when TomTom sets the closest waypoint it chooses the waypoint in your current zone. This option will cause TomTom to search for any waypoints on your current continent. This may lead you outside your current zone, so it is disabled by default."] = "Normalement, lorsque TomTom d\195\169finit le plus proche point de passage il choisit le point dans votre zone actuelle. Cette option fera que TomTom va rechercher les points de passage en dehors de votre zone actuelle, elle est donc d\195\169sactiv\195\169e par d\195\169faut.", -- Needs review
	["Options profile"] = "Options de profil", -- Needs review
	["Options that alter quest objective integration"] = "Options qui modifient l\226\128\153int\195\169gration des objectifs de qu\195\170tes", -- Needs review
	["Options that alter the coordinate block"] = "Options qui modifient le cadre de vos coordonn\195\169es", -- Needs review
	["Play a sound when arriving at a waypoint"] = "Jouer un son lors de l'arriv\195\169e \195\160 un point de passage", -- Needs review
	["Player coordinate accuracy"] = "Vos coordonn\195\169es en mode pr\195\169cision", -- Needs review
	["Player Coordinates"] = "Vos coordonn\195\169es", -- Needs review
	["Profile Options"] = "options du profil", -- Needs review
	["Prompt before accepting sent waypoints"] = "Demander avant d'accepter d'envoy\195\169 un point de passage", -- Needs review
	-- ["Provide a LDB data source for coordinates"] = "",
	-- ["Provide a LDB data source for the crazy-arrow"] = "",
	["Quest Objectives"] = "Objectifs de qu\195\170tes", -- Needs review
	["Remove all waypoints"] = "Retirez tous les points de passage", -- Needs review
	["Remove all waypoints from this zone"] = "Retirez tous les points de passage de cette zone", -- Needs review
	["Removed %d waypoints from %s"] = "Suppression de %d du point de passage %s", -- Needs review
	["Remove waypoint"] = "Retirer le point", -- Needs review
	["Reset Position"] = "R\195\169initialiser la position", -- Needs review
	["Resets the position of the waypoint arrow if its been dragged off screen"] = "R\195\169initialise la position de la fl\195\168che si elle a \195\169t\195\169 tra\195\174n\195\169e hors de l'\195\169cran", -- Needs review
	["Reset waypoint display options to current"] = "R\195\169initialiser les options d'affichage du point de passage actuel", -- Needs review
	["%s (%.2f, %.2f)"] = "%s (%.2f, %.2f)", -- Needs review
	["Saved profile for TomTom options"] = "Profil enregistr\195\169 pour les options TomTom", -- Needs review
	["Save new waypoints until I remove them"] = "Enregistre de nouveau point de passage jusqu'\195\160 ce que je les supprime", -- Needs review
	["Save profile for TomTom waypoints"] = "Enregistrer le profil de TomTom des points de passage", -- Needs review
	["Save this waypoint between sessions"] = "Enregistrer ce point entre deux sessions", -- Needs review
	["Scale"] = "\195\137chelle", -- Needs review
	["Send to battleground"] = "Envoyer \195\160 champ de bataille", -- Needs review
	["Send to guild"] = "Envoyer \195\160 guilde", -- Needs review
	["Send to party"] = "Envoyer au groupe", -- Needs review
	["Send to raid"] = "Envoyer au raid", -- Needs review
	["Send waypoint to"] = "Envoyer un point de passage \195\160", -- Needs review
	["Set as waypoint arrow"] = "D\195\169finir comme point de passage ", -- Needs review
	-- ["set waypoint modifier"] = "",
	["Show estimated time to arrival"] = "Afficher l'heure estim\195\169e d'arriv\195\169e", -- Needs review
	["Shows an estimate of how long it will take you to reach the waypoint at your current speed"] = "Affiche une estimation de combien de temps il vous faudra pour atteindre le point \195\160 votre vitesse actuelle", -- Needs review
	["Shows the distance (in yards) to the waypoint"] = "Affiche la distance (en m\195\168tres) vers le point", -- Needs review
	["Show the distance to the waypoint"] = "Indiquer \195\160 quelle distance du point.", -- Needs review
	["%s: No coordinate information found for '%s' at this map level"] = "%s: Aucune information coordonn\195\169e trouv\195\169e pour '%s' \195\160 ce niveau de la carte", -- Needs review
	["%sNo waypoints in this zone"] = "%sPas de points dans cette zone", -- Needs review
	["%s%s - %s (map: %d, floor: %d)"] = "%s%s - %s (carte: %d, sol: %d)", -- Needs review
	["%s yards away"] = "%d m\195\168tres", -- Needs review
	["The color to be displayed when you are halfway between the direction of the active waypoint and the completely wrong direction"] = "La couleur \195\160 afficher lorsque vous \195\170tes \195\160 mi-chemin entre la direction du point actif et le point de d\195\169part", -- Needs review
	["The color to be displayed when you are moving in the direction of the active waypoint"] = "La couleur \195\160 afficher lorsque vous vous d\195\169placez dans la direction du point actif", -- Needs review
	["The color to be displayed when you are moving in the exact direction of the active waypoint"] = "La couleur qui s'affiche lorsque vous vous d\195\169placez dans la direction exacte du point actif", -- Needs review
	["The color to be displayed when you are moving in the opposite direction of the active waypoint"] = "La couleur \195\160 afficher lorsque vous vous d\195\169placez dans la direction oppos\195\169e du point actif", -- Needs review
	["The display of the coordinate block can be customized by changing the options below."] = "L'affichage du cadre de vos coordonn\195\169es peut \195\170tre personnalis\195\169 en changeant les options ci-dessous.", -- Needs review
	["The floating waypoint arrow can change color depending on whether or nor you are facing your destination.  By default it will display green when you are facing it directly, and red when you are facing away from it.  These colors can be changed in this section.  Setting these options to the same color will cause the arrow to not change color at all"] = "La fl\195\168che flottante peut changer de couleur selon votre direction. Par d\195\169faut, elle affichera en vert lorsque vous \195\170tes face au point, et rouge quand vous \195\170tes \195\169loign\195\169. Ces couleurs peuvent \195\170tre modifi\195\169es dans cette section.", -- Needs review
	["There were no waypoints to remove in %s"] = "Il n'y avait aucun point de passage \195\160 supprimer dans %s", -- Needs review
	["These options let you customize the size and opacity of the waypoint arrow, making it larger or partially transparent, as well as limiting the size of the title display."] = "Ces options vous permettent de personnaliser la taille et l'opacit\195\169 de la fl\195\168che, ainsi que la limitation de la taille de l'affichage du titre.", -- Needs review
	["This option will not remove any waypoints that are currently set to persist, but only effects new waypoints that get set"] = "Cette option ne supprime pas tous les points qui sont actuellement fix\195\169s, mais ne concerne que les nouveaux points de passage que vous fix\195\169s", -- Needs review
	["This option will toggle whether or not you are asked to confirm removing all waypoints.  If enabled, a dialog box will appear, requiring you to confirm removing the waypoints"] = "Cette option permet de basculer si oui ou non vous \195\170tes invit\195\169 \195\160 confirmer la suppression de tous les points de passage. Si elle est activ\195\169e, une bo\195\174te de dialogue s'affiche, vous demandant de confirmer la suppression des points.", -- Needs review
	["This setting allows you to change the opacity of the title text, making it transparent or opaque"] = "Ce r\195\169glage vous permet de modifier l'opacit\195\169 du texte du titre", -- Needs review
	["This setting allows you to change the opacity of the waypoint arrow, making it transparent or opaque"] = "Ce r\195\169glage vous permet de modifier l'opacit\195\169 de la fl\195\168che", -- Needs review
	["This setting allows you to change the scale of the waypoint arrow, making it larger or smaller"] = "Ce param\195\168tre vous permet de modifier l'\195\169chelle de la fl\195\168che", -- Needs review
	["This setting allows you to specify the maximum height of the title text.  Any titles that are longer than this height (in game pixels) will be truncated."] = "Ce param\195\168tre vous permet de sp\195\169cifier la hauteur maximale du titre.", -- Needs review
	["This setting allows you to specify the maximum width of the title text.  Any titles that are longer than this width (in game pixels) will be wrapped to the next line."] = "Ce param\195\168tre vous permet de sp\195\169cifier la largeur maximale du titre. ", -- Needs review
	["This setting allows you to specify the scale of the title text."] = "Ce param\195\168tre vous permet de sp\195\169cifier l'\195\169chelle du titre.", -- Needs review
	["This setting changes the modifier used by TomTom when right-clicking on a quest objective POI to create a waypoint"] = "Ce param\195\168tre modifie le modificateur utilis\195\169 par TomTom, un clic droit sur un objectif de qu\195\170te pour cr\195\169er un point de passage.", -- Needs review
	["This setting changes the modifier used by TomTom when right-clicking on the world map to create a waypoint"] = "Ce param\195\168tre modifie le modificateur utilis\195\169 par TomTom, un clic droit sur la carte du monde pour cr\195\169er un point de passage.", -- Needs review
	["This setting will control the distance at which the waypoint arrow switches to a downwards arrow, indicating you have arrived at your destination"] = "Ce param\195\168tre contr\195\180le la distance \195\160 laquelle la fl\195\168che passe \195\160 une fl\195\168che vers le bas, ce qui indique que vous \195\170tes arriv\195\169 \195\160 votre destination.", -- Needs review
	["Title Alpha"] = "Titre alpha", -- Needs review
	["Title Height"] = "Hauteur du titre", -- Needs review
	["Title Scale"] = "\195\137chelle du Titre", -- Needs review
	["Title Width"] = "Largeur du titre", -- Needs review
	["TomTom can announce new waypoints to the default chat frame when they are added"] = "TomTom peut annoncer de nouveaux points dans la fen\195\170tre de discussion (par d\195\169faut) lorsqu'ils sont ajout\195\169s", -- Needs review
	["TomTom can automatically set a waypoint when you die, guiding you back to your corpse"] = "TomTom peut d\195\169finir automatiquement un point de passage lorsque vous mourrez, il vous guide vers votre corps", -- Needs review
	["TomTom can be configured to set waypoints for the quest objectives that are shown in the watch frame and on the world map.  These options can be used to configure these options."] = "TomTom peut \195\170tre configur\195\169 pour d\195\169finir les points pour des objectifs de qu\195\170te qui sont affich\195\169es sur la carte du monde. ", -- Needs review
	["TomTom can display a tooltip containing information abouto waypoints, when they are moused over.  This setting toggles that functionality"] = "TomTom peut afficher une infobulle contenant des informations sur les points de passage. Ce param\195\168tre active ou d\195\169sactive cette fonctionnalit\195\169", -- Needs review
	["TomTom can display multiple waypoint arrows on the minimap.  These options control the display of these waypoints"] = "TomTom peut afficher plusieurs points sur la minicarte. Ces options contr\195\180lent l'affichage de ces points de passage", -- Needs review
	["TomTom can display multiple waypoints on the world map.  These options control the display of these waypoints"] = "TomTom peut afficher plusieurs points sur la carte du monde. Ces options contr\195\180lent l'affichage de ces points de passage", -- Needs review
	["TomTom can hide waypoints in other zones, this setting toggles that functionality"] = "Vous pouvez masquer les points dans d'autres zones, ce param\195\168tre s'active ou d\195\169sactive cette fonctionnalit\195\169", -- Needs review
	["TomTom is capable of providing data sources via LibDataBroker, which allows them to be displayed in any LDB compatible display.  These options enable or disable the individual feeds, but will only take effect after a reboot."] = "TomTom est capable de fournir des sources de donn\195\169es par l'interm\195\169diaire de LibDataBroker, qui lui permet d'\195\170tre affich\195\169es dans un affichage LDB compatible. Ces options active ou d\195\169sactive le flux individuel, mais ne prendra effet qu'apr\195\168s un red\195\169marrage.", -- Needs review
	["TomTom provides an arrow that can be placed anywhere on the screen.  Similar to the arrow in \"Crazy Taxi\" it will point you towards your next waypoint"] = "TomTom affiche une fl\195\168che qui peut \195\170tre plac\195\169e n'importe o\195\185 sur votre \195\169cran. Elle vous dirigera vers votre prochain point de passage.",
	["TomTom provides you with a floating coordinate display that can be used to determine your current position.  These options can be used to enable or disable this display, or customize the block's display."] = "TomTom vous offre un affichage de vos coordonn\195\169es dans une fen\195\170tre flottante qui peut \195\170tre utilis\195\169 pour d\195\169terminer votre position actuelle. Ces options peuvent \195\170tre utilis\195\169es pour activer ou d\195\169sactiver cet affichage, ou la personnaliser.", -- Needs review
	["TomTom's saved variables are organized so you can have shared options across all your characters, while having different sets of waypoints for each.  These options sections allow you to change the saved variable configurations so you can set up per-character options, or even share waypoints between characters"] = "TomTom enregistre et organise afin que vous puissiez avoir des options communes \195\160 travers tous vos personnages, tout en ayant diff\195\169rents ensembles de points pour chacun. Cette section vous permet de modifier les configurations enregistr\195\169es de sorte que vous pouvez configurer les options par personnage, ou encore partager des points de passage entre vos personnages.", -- Needs review
	["TomTom waypoint"] = "TomTom point de passage", -- Needs review
	["TomTom Waypoint Arrow"] = "Fl\195\168che TomTom point de passage", -- Needs review
	["Unknown distance"] = "Distance inconnue", -- Needs review
	["Unknown waypoint"] = "Points de passage inconnus", -- Needs review
	["Update throttle"] = "Mise \195\160 jour", -- Needs review
	["Wayback"] = "Chemin du retour", -- Needs review
	["Waypoint Arrow"] = "Fl\195\168che directionnelle", -- Needs review
	["Waypoint communication"] = "Communication du point de passage", -- Needs review
	["Waypoint from %s"] = "Point de passe \195\160 partir de %s", -- Needs review
	["Waypoint Options"] = "Options du point de passage", -- Needs review
	["Waypoints can be automatically cleared when you reach them.  This slider allows you to customize the distance in yards that signals your \"arrival\" at the waypoint.  A setting of 0 turns off the auto-clearing feature\\Changing this setting only takes effect after reloading your interface."] = "Les points de passage peuvent \195\170tre automatiquement effac\195\169s lorsque vous les avez atteints.\194\160 Ce curseur vous permet de personnaliser la distance en m\195\168tres qui vous signale votre \194\171arriv\195\169e\194\187.\194\160 Une valeur de 0 d\195\169sactive la fonction.\\La modification de ce param\195\168tre ne prend effet qu'apr\195\168s le rechargement de votre interface.", -- Needs review
	["Waypoints profile"] = "Profil des points de passage", -- Needs review
	["When a new waypoint is added, TomTom can automatically set the new waypoint as the \"Crazy Arrow\" waypoint."] = "Quand un nouveau point est ajout\195\169, TomTom peut r\195\169gler automatiquement le nouveau point de la \"Fl\195\168che Crazy\".", -- Needs review
	["When a pet battle begins, the crazy arrow will be hidden from view. When you exit the pet battle, it will be re-shown."] = "Quand un combat de mascotte commence, la fl\195\168che sera cach\195\169. Lorsque vous quittez combat, elle sera r\195\169-affich\195\169.", -- Needs review
	["When the current waypoint is cleared (either by the user or automatically) and this option is set, TomTom will automatically set the closest waypoint in the current zone as active waypoint."] = "Lorsque le point de passage actuel est effac\195\169 (soit par l'utilisateur ou automatiquement) et si cette option est activ\195\169e, TomTom va automatiquement r\195\169gler le point de cheminement le plus proche dans la zone actuelle comme point actif.", -- Needs review
	-- ["When the player is dead and has a waypoint towards their corpse, it will prevent other waypoints from changing the crazy arrow"] = "",
	["When you 'arrive' at a waypoint (this distance is controlled by the 'Arrival Distance' setting in this group) a sound can be played to indicate this.  You can enable or disable this sound using this setting."] = "Lorsque vous arrivez sur un point de passage, un son peut \195\170tre jou\195\169 pour l'indiquer. Vous pouvez activer ou d\195\169sactiver le son \195\160 l'aide de ce param\195\168tre.", -- Needs review
	["World Map"] = "Carte de monde", -- Needs review
	["Yes"] = "Oui", -- Needs review
	["You are at (%s) in '%s' (map: %d, floor: %d)"] = "Vous \195\170tes \195\160 (%s) dans '%s' (carte: %d, Sol: %d)", -- Needs review
}

setmetatable(TomTomLocals, {__index=function(t,k) rawset(t, k, k); return k; end})

end
